# The deployment specification for nginx-ingress with the Check Point Alpine Module
# To expose the Ingress controller pods, you can use a different service configuration, according to this guide:
# https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-ingress-ctl
  namespace: {{.Release.Namespace}}
  annotations:
    agentVersion: {{ .Chart.Version }}
    openshift.io/scc: waap-scc-priv
  labels:
    app.kubernetes.io/name: nginx-ingress-ctl
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  selector:
   matchLabels:
     app: nginx-ingress
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      volumes:                          
        - name: dshm
          emptyDir:
            medium: Memory
      serviceAccountName: {{.Values.operatorServiceAccount.name}}
      containers:
      - args:
        - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
        - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: "{{.Values.image.cpappsecnginxingress.properties.imageRepo}}:{{ .Values.image.cpappsecnginxingress.properties.imageTag }}"
        imagePullPolicy: IfNotPresent
        name: {{.Release.Name}}-cp-nginx-container
        volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --token
        - {{ required "CloudGuard AppSec nanoToken required" .Values.nanoToken}}
        command:
        - /cp-nano-agent
        image: "{{.Values.image.cpappsecnanoagent.properties.imageRepo}}:{{.Values.image.cpappsecnanoagent.properties.imageTag}}"
        imagePullPolicy: IfNotPresent
        name: {{.Release.Name}}-cp-nano-container
        volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
